import Config from 'react-native-config';

export const config = {
  RAZORPAY_LIVE_KEY: Config.RAZORPAY_LIVE_KEY,
  RAZORPAY_TEST_KEY: Config.RAZORPAY_TEST_KEY,
  STRIPE_TEST_KEY: Config.STRIPE_TEST_KEY,
  STRIPE_LIVE_KEY: Config.STRIPE_LIVE_KEY,
  EXCHANGE_RATE_API_KEY: Config.EXCHANGE_RATE_API_KEY,
  BASE_URL: Config.BASE_URL,
  BASE_URL_LOCAL: Config.BASE_URL_LOCAL,
};
